### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by daxil34** [zS1L3NT/ts-discord-soundroid#3]
### Tell me about the feature you are requesting!

short commands like! play =! p

**Comment by zS1L3NT** [comment]
Sure, I'll start working on this

**Comment by zS1L3NT** [comment]
With the latest commit, SounDroid now use aliases for all message commands. The alias for every message command can be customised using the slash command `/set alias`. Custom aliases for message commands are unique to each server, so the alias you set in one server will not work in another server until the alias is set.

https://github.com/zS1L3NT/ts-discord-soundroid/commit/ac1a120b5c641c92a9ff0c8b1f509a8b98104401
